-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwcUBdAenp9mpR6RA
WCzDf0rY5IhFSlN1sAzk6QeEhdOgCgYIKoZIzj0DAQehRANCAAQuTV0WQTJWmqSX
H4KKGpo7K9OHxNUHP1pay6kk/ttMfOqdPRR/EaVVdXHL4bO4ceY7DWc6wC5Had4g
5JSJJXB4
-----END PRIVATE KEY-----